class FieldNames:
    ds_name = "Name"
    network_attacks = "Network Attacks"
    host_attacks = "Host Attacks"
    start_year = "Start Year"
    end_year = "End Year"
    ds_setting = "Setting"
    os_types = "OS Type"
    network_src = "Network Data Source"
    network_label = "Network Data Labeled"
    host_src = "Host Data Source"
    host_label = "Host Data Labeled"
    atk_categories = "Attack Categories"
    benign_activity = "Benign Activity"
    packed_size = "Packed Size in MB"
    unpacked_size = "Unpacked Size in MB"
